version: 2.1
jobs:
  # Job to test package
  build_test:
    docker:
      - image: circleci/python:3.8.10
    steps:
      - checkout
      - run:
          command: |
            python setup.py sdist bdist_wheel
            sudo pip install pipenv
            pipenv install dist/pkg_temperature_convrsn-0.0.1-py3-none-any.whl
            pipenv install pytest
      - run:
          command: |
            pipenv run pytest
  # Job to publish package on testpypi
  test_pypi_publish:
    docker:
      - image: circleci/python:3.8.10
    steps:
      - checkout
      - run:
          command: |
            python setup.py sdist bdist_wheel
            sudo pip install pipenv
            pipenv install twine
            pipenv run twine upload --repository testpypi dist/*
workflows:
  build_test_publish:
    jobs:
      - build_test
      - test_pypi_publish:
          # require package test succesfully
          requires:
            - build_test
          filters:
            branches:
              only:
                - main